### ISSUE TITLE
pre-trained PWC-Net model on KITTI.

### ISSUE THREAD

**Issue by lixiangyu-1008** [philferriere/tfoptflow#12]
hi @philferriere  
thanks for your work on PWC-Net, Do you have the pre-trained model on KITTI ?

**Comment by LiuzhuForFun** [comment]
Hi,Did you solve it

**Comment by lixiangyu-1008** [comment]
@LiuzhuForFun hi, I have finetune the model on KITTI by myself.

**Comment by atanas1054** [comment]
Can you please give some code on how to finetune a model on KITTI?

**Comment by wohaiyo** [comment]
@lixiangyu-1008 Hello, could you share with me the finetuned model on KITTI?

**Comment by lixiangyu-1008** [comment]
hi @wohaiyo  By email or any other way?

**Comment by wohaiyo** [comment]
Thanks for your kind help @lixiangyu-1008 email:mwgwohaiyo@gmail.com or google drive link.

**Comment by lixiangyu-1008** [comment]
@wohaiyo  please check your email :)

**Comment by xuleyoung** [comment]
@lixiangyu-1008 hello, I aslo need your kind help,would you share some code about finetune, I meet some problems about finetune code, my email : 617104820@qq.com,Thank you~

**Comment by DanieleMenchetti** [comment]
@lixiangyu-1008  Hello, could you share with me the finetuned model on KITTI you made, please? 
I would appreciate it a lot! :)


Here is my email: danielemenchetti123@gmail.com

**Comment by andersonhusky** [comment]
@lixiangyu-1008  Hello! I need to finetuned model on KITTI too, could you please share your code about finetune the model, 
 thansk a lot!
my email: hogfeg@zju.edu.cn
