### ISSUE TITLE
tfoptflow vs nvlabs realization 

### ISSUE THREAD

**Issue by efyphil** [philferriere/tfoptflow#17]
Hello, thank you for your work, I've decided to compare 2 implementations, yours and the official one, and I've got quite different results on Kitty's datset, you can comment on it somehow, thank you. 
![Screenshot from 2019-04-23 19-37-37](https://user-images.githubusercontent.com/38631588/56600067-9659a000-6600-11e9-8199-f650f96bcc65.png)
![Screenshot from 2019-04-23 20-34-05](https://user-images.githubusercontent.com/38631588/56603194-df612280-6607-11e9-8174-619b71190b5e.png)

**Comment by xianshunw** [comment]
which one is from nvlabs?

**Comment by efyphil** [comment]
https://github.com/NVlabs/PWC-Net official

**Comment by xianshunw** [comment]
emm..  I mean which result you posted is from nvlabs.

**Comment by efyphil** [comment]
Oh, sorry, the better result was from nvlabs, second one
