### ISSUE TITLE
Optical flow color code

### ISSUE THREAD

**Issue by jeffbaena** [philferriere/tfoptflow#20]
Dear authors,
 thank you for your great work, it is very useful for me!
I found an issue on flow visualization. I found that the color code is correct in most cases, but when there is only vertical motion moving downwards, the color displayed is green and not yellow as depicted in the colorwheel. I have further tested this situation with the middlebury original code and I can confirm that the matlab script (http://vision.middlebury.edu/flow/submit/) produces yellow output for objects moving downwards.

Could you help me find the reason for that?

In addition, when testing on sintel I can see that the groundtruth visualization slighlty differs from yours (both if normalized= True of False, false gives worse results)

Regards,
Stefano

Attach an example on sintel:

<img width="999" alt="Screenshot 2019-06-13 at 19 15 45" src="https://user-images.githubusercontent.com/18122010/59453259-cf97da80-8e0f-11e9-805a-18a9071221f4.png">

your script with flo_v =100
<img width="222" alt="Screenshot 2019-06-13 at 19 16 17" src="https://user-images.githubusercontent.com/18122010/59453287-dfafba00-8e0f-11e9-9573-6d2bde3199c2.png">

matlab script with flo_v =100

<img width="214" alt="Screenshot 2019-06-13 at 19 16 32" src="https://user-images.githubusercontent.com/18122010/59453315-eb02e580-8e0f-11e9-88f3-198ccd5e845c.png">

**Comment by jeffbaena** [comment]
I have found a solution using the script from another repository. If someone needs it I can send it

**Comment by Becomebright** [comment]
@jeffbaena Hi, could you please share the script with me? My email is shangzhe.di@gmail.com. Thanks a lot.

**Comment by andreitapch** [comment]
@jeffbaena Hi!, could you please share the script with me? my email is andreitapch@hotmail.com
Thanks
