### ISSUE TITLE
FlyingThingsHalfRes cannot be generated

### ISSUE THREAD

**Issue by jeffbaena** [philferriere/tfoptflow#26]
Could someone help with this issue? 

_Originally posted by @Ecalpal in https://github.com/philferriere/tfoptflow/issues/9

**Comment by jeffbaena** [comment]
I might have found the issue:
FlyingThings3DHalfResDataset(mode='train_with_val', ds_root=FLYINGTHINGS3DHALFRES_ROOT, options=ds_opts)

ds_root should be tuple: e.g. in my case: ds_root=('path_to_flyingthings',FLYINGTHINGS3DHALFRES_ROOT)

I hope it helps

**Comment by Ecalpal** [comment]
> I might have found the issue:
> FlyingThings3DHalfResDataset(mode='train_with_val', ds_root=FLYINGTHINGS3DHALFRES_ROOT, options=ds_opts)
> 
> ds_root should be tuple: e.g. in my case: ds_root=('path_to_flyingthings',FLYINGTHINGS3DHALFRES_ROOT)
> 
> I hope it helps

Hi, Stefano,
This dataset is not things3d. You can look at this issue

[https://github.com/NVlabs/PWC-Net/issues/44](url)

>  FlyingThings3DHalfRes is our own version of FlyingThings3D where every input image pair and groundtruth flow has been downsampled by two in each dimension.

I have tried to downsampled them and resize the shape as Chairs, and put chairs and the new things3d to a same dataset to train a new model.

I hope it helps

**Comment by jeffbaena** [comment]
Yes, FLYINGTHINGS3DHALFRES_ROOT is computed by the authors when the script are run the first time, I think you do not need to downsample yourself (it will be a pain to create all the paths properly). If I am not mistaken,when calling the instance FlyingThings3DHalfResDataset(......) to make it work you need the parameter ds_root to be a tuple of strings.
I can tell you by tomorrow if everything worked fine.

If you are not convinced, try to look at the file dataset_flyingthings3d.py at line 147

Bests,
Stefano

**Comment by Ecalpal** [comment]
> Yes, FLYINGTHINGS3DHALFRES_ROOT is computed by the authors when the script are run the first time, I think you do not need to downsample yourself (it will be a pain to create all the paths properly). If I am not mistaken,when calling the instance FlyingThings3DHalfResDataset(......) to make it work you need the parameter ds_root to be a tuple of strings.
> I can tell you by tomorrow if everything worked fine.
> 
> If you are not convinced, try to look at the file dataset_flyingthings3d.py at line 147
> 
> Bests,
> Stefano

I'm sorry for my carelessness. 
If you get any improvement, please tell me, my email is fengcheng00016@163.com.
Thanks!

**Comment by jeffbaena** [comment]
@Ecalpal  ,mine should be the correct answer. Just change ds_path='your_path_to_half_res' to ds_path=('your_path_to_full_res' ,'your_path_to_half_res' ). This should do the trick, the code expects a tuple the first time you load the script.

Let me know how it goes!
