### ISSUE TITLE
A question about FlyingThings3D

### ISSUE THREAD

**Issue by Ecalpal** [philferriere/tfoptflow#9]
Hi, Phil !
This project is a great work. I've learned a lot from it. Few days ago, I tested it in the FlyingChairs, it works well. Yesterday I downloaded the FlyingThings and modified my train.py according to pwcnet_train_sm-6-2-multisteps-chairsthingsmix.ipynb. When I run it, a problem has arisen.

`
server1@server1-All-Series:/disk_2t/pwc_f$ python train_mix.py 
Traceback (most recent call last):
  File "train_mix.py", line 36, in <module>
    ds2 = FlyingThings3DHalfResDataset(mode='train_with_val', ds_root=_FLYINGTHINGS3DHALFRES_ROOT, options=ds_opts)
  File "/disk_2t/pwc_f/dataset_flyingthings3d.py", line 155, in __init__
    super().__init__(mode, ds_root, options)
  File "/disk_2t/pwc_f/dataset_flyingthings3d.py", line 41, in __init__
    super().__init__(mode, ds_root, options)
  File "/disk_2t/pwc_f/dataset_base.py", line 128, in __init__
    self.prepare()
  File "/disk_2t/pwc_f/dataset_base.py", line 203, in prepare
    self._build_ID_sets()
  File "/disk_2t/pwc_f/dataset_flyingthings3d.py", line 188, in _build_ID_sets
    if self.generate_files is True:
AttributeError: 'FlyingThings3DHalfResDataset' object has no attribute 'generate_files'
`

I think it is caused by the wrong path of dataset. My path looks like this.

server1@server1-All-Series:/disk_2t/dataset$ ls
FlyingChairs_release  FlyingThings3D_HalfRes

server1@server1-All-Series:/disk_2t/dataset/FlyingThings3D_HalfRes$ ls
all_unused_files.txt  frames_cleanpass  optical_flow

and in train.py, I define the path like this.

_DATASET_ROOT = '/disk_2t/dataset/'
_FLYINGCHAIRS_ROOT = _DATASET_ROOT + 'FlyingChairs_release'
_FLYINGTHINGS3DHALFRES_ROOT = _DATASET_ROOT + 'FlyingThings3D_HalfRes'

Could you tell me what I did wrong? 
Thank you!

**Comment by jeffbaena** [comment]
@Ecalpal  I have the same issue in generating the dataset, could you tell me how you solved it ?

Thanks,
Stefano

**Comment by Ecalpal** [comment]
> @Ecalpal I have the same issue in generating the dataset, could you tell me how you solved it ?
> 
> Thanks,
> Stefano

Hi, Stefano!
I haven't used this framework for a long time. I used to create the same data set in the way he said, but the effect is not so good. Maybe there's something wrong with my operation.

**Comment by jeffbaena** [comment]
I understand, I think it just might be a wrong flag in "dataset_flyingthings3d.py", I'll check it out.
Thanks for your prompt response!

Stefano

**Comment by Blcony** [comment]
@Ecalpal 
Hi, Ecalpal!
Have you tried any other codes about PWC-net besids this one?
From the issues, I think there are some bugs in codes, so I want to konw whether there are better codes about PWC-net.
Thanks a lot!

**Comment by jeffbaena** [comment]
If you can use caffe I think you can try the original implementation (caffe is very painful to me). If you only need inference I think the best is https://github.com/sniklaus/pytorch-pwc, I have used it and tested it and it works good.

If you need to train I think this is the best implementation...there are many bugs but it still is the best. Please let me know if you have any updates

Cheers,
Stefano

**Comment by Ecalpal** [comment]
> @Ecalpal
> Hi, Ecalpal!
> Have you tried any other codes about PWC-net besids this one?
> From the issues, I think there are some bugs in codes, so I want to konw whether there are better codes about PWC-net.
> Thanks a lot!

@Blcony 
Hi,
I wrote one myself in pytorch, 
it's hard to imagine you're from utsc, because there aren't many people studying optical flow in China.
This is the best implementation of tensorflow, I rewrote the difficult data pipeline, and used it for a long time.

**Comment by Blcony** [comment]
> If you can use caffe I think you can try the original implementation (caffe is very painful to me). If you only need inference I think the best is https://github.com/sniklaus/pytorch-pwc, I have used it and tested it and it works good.
> 
> If you need to train I think this is the best implementation...there are many bugs but it still is the best. Please let me know if you have any updates
> 
> Cheers,
> Stefano

Thanks a lot !
Your suggestions are very helpful for me !

**Comment by Blcony** [comment]
> > @Ecalpal
> > Hi, Ecalpal!
> > Have you tried any other codes about PWC-net besids this one?
> > From the issues, I think there are some bugs in codes, so I want to konw whether there are better codes about PWC-net.
> > Thanks a lot!
> 
> @Blcony
> Hi,
> I wrote one myself in pytorch,
> it's hard to imagine you're from utsc, because there aren't many people studying optical flow in China.
> This is the best implementation of tensorflow, I rewrote the difficult data pipeline, and used it for a long time.

Thanks for your replying !

I just start to study the optical flow, and your suggestions mean a lot for me.

So have you got results that match the official results (including the performance fientuned on Sinte/Kitti) after your reimplement?

And the core modification of this code is the data pipeline ? Or something else ? Because I have seen many bugs in codes according to issues, I am more concerned about the modification about codes.
Thanks a lot! I wish to hear from you soon!

Best wishes,
Bill Chou

**Comment by jeffbaena** [comment]
@Ecalpal any chance you might release your code on git? It would be very helpful for me and many others!

Regards,
Stefano

**Comment by Ecalpal** [comment]
> Shenglong Zhou

Hi,
I can't implement the official results on pytorch or tensorflow.
There are many factors involved, and I think the most critical is the data preprocessing part. Unfortunately, it is impossible to implement caffe's data enhancement.
Another key factor is the issue of frameworks. The official pytorch weight is also slightly worse than caffe's.
If you want to implementthe official results training from scratch, Caffe is the best choice.

Best wishes,
ChengFeng

**Comment by Ecalpal** [comment]
> > > @Ecalpal
> > > Hi, Ecalpal!
> > > Have you tried any other codes about PWC-net besids this one?
> > > From the issues, I think there are some bugs in codes, so I want to konw whether there are better codes about PWC-net.
> > > Thanks a lot!
> > 
> > 
> > @Blcony
> > Hi,
> > I wrote one myself in pytorch,
> > it's hard to imagine you're from utsc, because there aren't many people studying optical flow in China.
> > This is the best implementation of tensorflow, I rewrote the difficult data pipeline, and used it for a long time.
> 
> Thanks for your replying !
> 
> I just start to study the optical flow, and your suggestions mean a lot for me.
> 
> So have you got results that match the official results (including the performance fientuned on Sinte/Kitti) after your reimplement?
> 
> And the core modification of this code is the data pipeline ? Or something else ? Because I have seen many bugs in codes according to issues, I am more concerned about the modification about codes.
> Thanks a lot! I wish to hear from you soon!
> 
> Best wishes,
> Bill Chou

Hi,
I can't implement the official results on pytorch or tensorflow.
There are many factors involved, and I think the most critical is the data preprocessing part. Unfortunately, it is impossible to implement caffe's data enhancement.
Another key factor is the issue of frameworks. The official pytorch weight is also slightly worse than caffe's.
If you want to implementthe official results training from scratch, Caffe is the best choice.

Best wishes,
ChengFeng

**Comment by Ecalpal** [comment]
> @Ecalpal any chance you might release your code on git? It would be very helpful for me and many others!
> 
> Regards,
> Stefano

Hi,
Although my code completed the entire training process (Chairs-Things3d-Sintel), it still failed to achieve the official results.
I think it's a failure, and there must be some mistakes in it. It's been in the corner of my computer for a long time. I don't think it should be released to mislead others.

Regards,
ChengFeng

**Comment by jeffbaena** [comment]
@Ecalpal all right, thanks for your reply! I also faced the data augmentation issue when trying to improve flownet.  But I do not think your code is a failure, really! Sometimes just with some parameters tweaking you can observe really good improvements.

If you need...I found very useful this repo for data augmentation https://github.com/ucbdrive/hd3
I have adapted their code to add random scale data augmentation(the link was curtesy of @guuuus)

Bests,
Stefano

**Comment by Ecalpal** [comment]
> @Ecalpal all right, thanks for your reply! I also faced the data augmentation issue when trying to improve flownet. But I do not think your code is a failure, really! Sometimes just with some parameters tweaking you can observe really good improvements.
> 
> If you need...I found very useful this repo for data augmentation https://github.com/ucbdrive/hd3
> I have adapted their code to add random scale data augmentation(the link was curtesy of @GuuuuS)
> 
> Bests,
> Stefano

I know who you mean, he is my classmate.
He can't implement the official results too.
I'll sort out the code and release it in a few days.

Bests,
ChengFeng

**Comment by jeffbaena** [comment]
Thanks for that,
 And the world is really small! You are very helpful people!

Thanks,
Stefano
